environments:
  dev: "https://automationexercise.com"
  prod: "https://automationexercise.com"

browsers:
  chrome:
    webdriver: "/Users/jackrosesmile/Documents/PythonProject/MyTestFramework/src/webdriver/chrome/chromedriver"
    binary_path: "/Applications/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"
  firefox:
    webdriver: "path/to/firefoxdriver"
    binary_path: "path/to/firefox"